import { and, eq, isNull } from 'drizzle-orm';
import { db } from '../../db/drizzle.js';
import { chats, chatParticipants, messages, reactions } from '../../db/schema/chats.js';
import type { CreateChatInput } from '@xolo/protocol';
const words = ['Azure', 'Brisk', 'Calm', 'Dawn', 'Ember'];
export const aliasFor = () => `${words[Math.floor(Math.random() * words.length)]}-${Math.floor(1000 + Math.random() * 9000)}`;
export async function createChat(userId: string, zoneKey: string, input: CreateChatInput) { const [chat] = await db.insert(chats).values({ creatorId: userId, zoneKey, type: input.type, title: input.title, memberCap: input.type === 'private' ? 2 : (input.memberCap ?? 50) }).returning(); await db.insert(chatParticipants).values({ chatId: chat.id, userId, alias: aliasFor() }); return chat; }
export async function participant(chatId: string, userId: string) { const [row] = await db.select().from(chatParticipants).where(and(eq(chatParticipants.chatId, chatId), eq(chatParticipants.userId, userId), isNull(chatParticipants.leftAt))).limit(1); return row; }
export async function joinChat(chatId: string, userId: string) { const [chat] = await db.select().from(chats).where(eq(chats.id, chatId)).limit(1); if (!chat || chat.status === 'closed') throw new Error('Chat is unavailable'); const current = await participant(chatId, userId); if (current) return { chat, participant: current }; const members = await db.select().from(chatParticipants).where(and(eq(chatParticipants.chatId, chatId), isNull(chatParticipants.leftAt))); if (members.length >= chat.memberCap || (chat.type === 'private' && chat.status !== 'open')) throw new Error('Chat is full'); const [member] = await db.insert(chatParticipants).values({ chatId, userId, alias: aliasFor() }).returning(); if (chat.type === 'private') await db.update(chats).set({ status: 'matched' }).where(eq(chats.id, chatId)); return { chat: { ...chat, status: chat.type === 'private' ? 'matched' : chat.status }, participant: member }; }
export async function addMessage(chatId: string, userId: string, body: string, clientId: string) { const [chat] = await db.select().from(chats).where(eq(chats.id, chatId)).limit(1); if (!chat || chat.status === 'closed' || !(await participant(chatId, userId))) throw new Error('You cannot message this chat'); const [message] = await db.insert(messages).values({ chatId, senderId: userId, body, clientId }).onConflictDoNothing().returning(); return message; }
export async function toggleReaction(messageId: string, userId: string, emoji: string) { const [message] = await db.select().from(messages).where(eq(messages.id, messageId)).limit(1); if (!message || !(await participant(message.chatId, userId))) throw new Error('You cannot react to this message'); const [found] = await db.select().from(reactions).where(and(eq(reactions.messageId, messageId), eq(reactions.userId, userId), eq(reactions.emoji, emoji))).limit(1); if (found) { await db.delete(reactions).where(eq(reactions.id, found.id)); return false; } await db.insert(reactions).values({ messageId, userId, emoji }); return true; }
